#!/usr/bin/env bash
set -eou pipefail

ticker='VEMAX'
date_range='2018-02-22|2018-02-25'
params='showVol=true&dtype=his'

curl "http://globalquote.morningstar.com/globalcomponent/RealtimeHistoricalStockData.ashx?ticker=${ticker}&range=${date_range}&${params}"
