#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )" && cd "$dir"
app="$(basename $dir)"

publish(){
  set +u; local tag="$1"; set -u
  local tag_suffix='dev'

  if [[ -z $tag ]]; then
    cat "${dir}/deploy/default/Dockerfile" >Dockerfile
    tag="$tag_suffix"
  else
    cat "${dir}/deploy/default/${tag}.Dockerfile" >Dockerfile
    tag="${tag}-${tag_suffix}"
  fi

  docker build --rm -t "${app}:${tag}" .
  docker tag "${app}:${tag}" "$app"

  if [[ -f Dockerfile ]]; then rm Dockerfile; fi
}

lein uberjar \
  && publish \
  && publish 'arm'
