#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app_name=$(basename $(dirname $dir))

# for live test
  #-e jdbc_db_uri="$(echo $jdbc_db_uri)" \

docker run --rm -it \
  --name="$(echo $app_name)" \
  -e jdbc_db_uri="$(echo 'jdbc:postgresql://192.168.99.100:5432/postgres?loginTimeout=30&socketTimeout=900&tcpKeepAlive=true&user=postgres')" \
  -e quandl_api_key="$(echo $quandl_api_key)" \
  -e docker_psql_uri="$(echo $docker_psql_uri)" \
  -e healthchecks_io_api_key="$(echo $healthchecks_io_api_key)" \
  "$app_name":dev bash
