#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )" && cd "$dir"
app="$(basename $dir)"

# live
  #-e jdbc_db_uri="$(echo $jdbc_db_uri)" \
# for test
  #-e jdbc_db_uri="$(echo 'jdbc:postgresql://192.168.99.100:5432/postgres?loginTimeout=30&socketTimeout=900&tcpKeepAlive=true&user=postgres')" \

docker run --rm -it \
  --name="$(echo $app_name)" \
  -e jdbc_db_uri="$(echo $jdbc_db_uri)" \
  -e quandl_api_key="$(echo $quandl_api_key)" \
  -e tiingo_api_key="$(echo $tiingo_api_key)" \
  -e alpha_vantage_api_key="$(echo $alpha_vantage_api_key)" \
  -e docker_psql_uri="$(echo $docker_psql_uri)" \
  -e healthchecks_io_api_key="$(echo $healthchecks_io_api_key)" \
  "$app":dev bash
