#!/usr/bin/env bash
set -eou pipefail

start="$SECONDS"

(lein cloverage --codecov && \
  bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json & 2>/dev/null; \
  lein test & 2>/dev/null; \
  lein cljfmt check & 2>/dev/null; wait) && wait && echo 'ready to deploy'

#(sleep 3 & 2>/dev/null; sleep 2 & 2>/dev/null; wait) && wait && echo 'here'

wait

echo "script took $(echo "$(( $SECONDS - $start ))" | bc) seconds to complete"
