#!/usr/bin/env bash
set -eou pipefail

ticker='VMRAX'
ticker='FB'
start_date='2018-08-20'
end_date='2018-08-31'
params="types=quote&range=1m&last=1"

# docs: https://www.barchart.com/ondemand/free-market-data-api
latest(){
  curl \
    "https://marketdata.websol.barchart.com/getHistory.json?apikey=YOUR_API_KEY&symbol=${ticker}&type=daily&startDate=20160608000000"
}

latest
