#!/usr/bin/env bash
set -eou pipefail

user=$(whoami)
dir="/home/${user}/deploy/app"
app=$(basename $(pwd) | sed -e 's/.git//')
deploy_dir="$dir/$app"

GIT_WORK_TREE="$deploy_dir" git checkout -f

mkdir -p "$deploy_dir" && cd "$deploy_dir"

## build steps here ##
case $(uname) in
  (Linux)
    sudo cp deploy/tasks/crontab "/etc/cron.d/$app" ;;
  (FreeBSD)
    sudo cp deploy/tasks/crontab "/var/cron/tabs/$app" ;;
esac
