#!/usr/bin/env bash
set -eou pipefail

table=''
db=''

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" && cd "$dir"
usage(){ echo "Usage: upload-csv: ${0} [--table <portfolio|markets>] [--database <dev|prod>]" 1>&2; exit 1; }
while [[ $# -gt 0 ]]; do
  case "$1" in
    -t|--table)    table="$2"; shift ;;
    -d|--database) db="$2"; shift ;;
    *) break ;;
  esac
  shift
done
if [[ -z $table ]] || [[ -z $db ]]; then usage; fi

upload(){
  local table="$1"
  local db="$2"
  local psql_uri=''

  case "$db" in
    prod )
      psql_uri="$(echo "$db_uri")" ;;
    dev | * )
      psql_uri="$(echo "$docker_psql_uri")" ;;
  esac

  case "$table" in
    markets | portfolio )
      psql "$psql_uri" \
        -v ON_ERROR_STOP=1 \
        -f "${dir}/${table}-upload.sql" ;;
    * )
      echo 'usage: ./upload-csv portfolio|markets dev|prod' && exit 1 ;;
  esac
}

upload "$table" "$db"
