#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" && cd "$dir"

source '/Users/skilbjo/dev/engineering/src/athena.user'

get_dw_portfolio(){
  psql $db_uri -AF',' -c 'select * from dw.portfolio_dim' | \
    ghead -n -1 >~/Downloads/file.csv
}

upload_portfolio_to_s3(){
  aws s3 cp \
    --profile skilbjo \
    ~/Downloads/file.csv s3://skilbjo-data/datalake/markets-etl/portfolio/file.csv
}

verify_results(){
  query 'select * from datalake.portfolio'
}

delete_artifacts(){
  rm ~/Downloads/file.csv
}

get_dw_portfolio \
  && upload_portfolio_to_s3 \
  && verify_results \
  && delete_artifacts
